#!/usr/bin/perl

use strict;
use warnings;

use IO::Socket::INET;

my $listener = IO::Socket::INET->new(
    LocalPort => 2303,
    Listen => 1024,
);

$SIG{CHLD} = "IGNORE";

while (1) {
    local $!;
    my $client = $listener->accept;

    unless ($client) {
        warn "Failed to accept new client: $!\n";
        sleep 10;
        next;
    }

    my $pid = fork();
    redo if $pid; # Parent gets the child PID, so go accept another sock

    warn "Fired up a child: $$";

    warn "Unable to fork, running single-process: $!"
        unless defined $pid;

    print STDERR "Opening socket to server\n";
    my $server = IO::Socket::INET->new(
        PeerAddr => '127.0.0.1:2003',
    );
    print STDERR "Done opening socket to server\n";

    if ($server) {
        my $ip_addr = $client->peerhost;
        while (my $input = <$client>) {
            if ($input =~ m{\b__TYPE__\b}) {
                $input =~ s{^(\w+)\.}{};
                my $type = $1;
                $input =~ S{\b__TYPE__\b}{$type}g;
            }
            $server->write($input);
        }

    } else {
        warn "Couldn't open connection to server: $!\n";
        $client->close;
        sleep 10;
    }


    if (defined $pid) { # We're in a child process
        warn "Shutting down $$";
        exit;
        last;
    }
}
